---
- name: Deploy Docker image
  hosts: localhost
  vars:
    docker_image: "docker.io/aryan1207/miniproject_aryan"
    docker_container_name: "spe_mini_project_container"
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Start Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        state: started
        tty: yes
        interactive: yes
